language: node_js
sudo: false
node_js:
  - 5.5
env:
  - PSC_VERSION=0.8.0
  - PSC_VERSION=0.7.6
install:
  - npm install purescript-$PSC_VERSION pulp bower -g
  - bower update
script:
  - pulp build

after_success:
  - >-
    test $TRAVIS_TAG &&
    psc-publish > .pursuit.json &&
    curl -X POST https://pursuit.purescript.org/packages \
      -d @.pursuit.json \
      -H 'Accept: application/json' \
      -H "Authorization: token ${GITHUB_TOKEN}"
