language: node_js
sudo: false
node_js:
  - 5.5
install:
  - npm install purescript pulp bower -g
  - bower update
script:
  - pulp build

after_success:
  - >-
    test $TRAVIS_TAG &&
    psc-publish > .pursuit.json &&
    curl -X POST http://pursuit.purescript.org/packages \
      -d @.pursuit.json \
      -H 'Accept: application/json' \
      -H "Authorization: token ${GITHUB_TOKEN}"
